-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtMfVhKcILmU1Vfvj
Mnl6f1fkRbVmZEY5OntzEOGNhdegCgYIKoZIzj0DAQehRANCAASqTZl2+HYBVNEI
dLIW6nFjeF2ZTY0/8ETd5O1yKgB6j4/cvglPgZwKUHxCHWULTQk0mF0ssK0Dape7
jRyVxI8X
-----END PRIVATE KEY-----